name: Deploy Production

on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PRODUCTION_GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.PRODUCTION_SERVICE_ACCOUNT_JSON }}
        export_default_credentials: true
    - name: Use gcloud CLI
      run: |
        gcloud functions deploy SendNotification --runtime go113 --trigger-http --region asia-northeast1
        
